String.toLocaleString({
    
	"it": {
		"%game-intro"           : "Join the <strong>Cupcakes!</strong>",
		"%restart-button"       : "Play Again",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Bilder tagna från Facebook.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-CUPCAKES #2048game",
		"%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
		'%2'                    : 'vanilla birthday',
    '%4'                    : 'christopher gegerfelt',
    '%8'                    : 'maria neuman',
    '%16'                   : 'valrhona blonde ganache',
    '%32'                   : 'chocolare peanut butter cheesecake',
    '%64'                   : 'chocolate mint fudge',
    '%128'                  : 'chocolate spider web',
    '%256'                  : 'toasted marshmallow',
    '%512'                  : 'cookies and creme',
    '%1024'                 : 'chocolate sundae',
    '%2048'                 : 'white chocolate peppermint',
		'%p0'                   : 'vanilla birthday',
    '%p4'                   : 'christopher gegerfelt',
    '%p8'                   : 'maria neuman',
    '%p16'                  : 'valrhona blonde ganache',
    '%p32'                  : 'choc. peanut butter cheesecake',
    '%p64'                  : 'choc. mint fudge',
    '%p128'                 : 'choc. spider web',
    '%p256'                 : 'toasted marshmallow',
    '%p512'                 : 'cookies and creme',
    '%p1024'                : 'choc. sundae',
    '%p2048'                : 'white choc. peppermint',
	},
	
	"en": {
		"%game-intro"           : "Kan du nå <strong>Awets</strong> nivå?",
		"%restart-button"       : "Spela igen",
		"%keep-playing-button"  : "Keep going",
		"%retry-button"         : "Retry",
		"%game-won"             : "You win!",
		"%game-over"            : "Game over!",
		"%game-explanation"     : "<strong class=\"important\">HUR MAN SPELAR:</strong> Använd <strong>piltangenterna</strong> för att flytta plattorna. När två plattor med samma ansikte rör varandra, <strong>uppgraderas de till en ny, bättre platta!</strong>",
		"%disclaimer"           : "<strong class=\"important\">Note:</strong> This site <a href=\"http://git.io/cupcakes\">git.io/cupcakes</a> is a spin-off of the official version of <a href=\"http://git.io/2048\">2048</a> created by <a href=\"http://gabrielecirulli.com\" target=\"_blank\">Gabriele Cirulli</a>.",
		"%credits"              : "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
		"%tweet1"               : "I scored \"",
		"%tweet2"               : "\" at 2048-CUPCAKES #2048game",
		"%tile-legend"          : "<strong class=\"important\">Nivå av plattor, från sämst till bäst:</strong>",
		'%2'                    : 'christopher gegerfelt',
    '%4'                    : 'maria neuman',
    '%8'                    : 'hampus sonesson',
    '%16'                   : 'jonathan johansson',
    '%32'                   : 'jack blossby',
    '%64'                   : 'emil lacroix',
    '%128'                  : 'danel temesghen',
    '%256'                  : 'tony ulin',
    '%512'                  : 'ante dybedahl',
    '%1024'                 : 'joachim toft',
    '%2048'                 : 'awet fesshaie',
		'%p0'                   : 'christopher gegerfelt',
    '%p4'                   : 'maria neuman',
    '%p8'                   : 'hampus sonesson',
    '%p16'                  : 'jonathan johansson',
    '%p32'                  : 'jack blossby',
    '%p64'                  : 'emil lacroix',
    '%p128'                 : 'danel temesghen',
    '%p256'                 : 'tony ulin',
    '%p512'                 : 'ante dybedahl',
    '%p1024'                : 'joachim toft',
    '%p2048'                : 'awet fesshaie',
	}

});
